import React, { useState } from 'react';
import './Product.scss';

import sample1 from '../../assets/images/d1.jpg';
import sample2 from '../../assets/images/i2.jpg';

import addToCartIcon from '../../assets/icons/addtocart.png';
import addToFavouriteIcon from '../../assets/icons/favourite.png';
import { useLocation } from 'react-router-dom';


import men from '../../assets/images/a4.jpeg';

const Product = () => {

    const menProducts = [
        {
            id: 1,
            img: men,
            productName: 'Printed T-shirt',
            productPrice: '499',
        },
        {
            id: 2,
            img: men,
            productName: 'Black Jeans',
            productPrice: '999',
        },
        {
            id: 3,
            img: men,
            productName: 'Fancy Trackpant',
            productPrice: '699',
        },
    ];

    const images = {
        img1 : sample1,
        img2 : sample2,
    }

    const location = useLocation(); // THIS FUNCTION ARRAY OF LOCATION OBJECTS OF URL

    const productId = parseInt(location.pathname.split("/")[4])  // FUNCTION TO GET THE PRODUCT ID FROM THE URL BAR (GENERATED BY CLICKING ON ANY PRODUCT)

    let currentProduct = menProducts.filter(products => products.id === productId);

    const [viewImg, setViewImg] = useState(images.img1);

    const [productQuantity, setProductQuantity] = useState(1);

    return (
        <div className="singleProductContainer">
            {
                <div className="singleProductBox">
                    <div className="leftSide">
                        <div className="imgScroll">
                            <img className={`scrollImg ${viewImg === images.img1 ? 'active' : 'inactive'}`} src={sample1} alt='' onClick={e=>setViewImg(images.img1)}></img>
                            <img className={`scrollImg ${viewImg === images.img2 ? 'active' : 'inactive'}`} src={sample2} alt='' onClick={e=>setViewImg(images.img2)}></img>
                        </div>
                        <div className="imgView">
                            <img src={viewImg} alt=''></img>
                        </div>
                    </div>
                    <div className="rightSide">
                        <div className="productName">{currentProduct[0].productName}</div>
                        <div className="productDescrip">Men's Cotton White Plain T-shirt with Supima Finishing</div>
                        <div className="productPrice">&#8377; {currentProduct[0].productPrice}</div>
                        <div className="priceNote">inclusive of all taxes</div>

                        <div className="productQuantity">
                            <button onClick={()=>setProductQuantity((prev)=> prev === 1 ? 1 : prev - 1)}>-</button>
                            <span>{productQuantity}</span>
                            <button onClick={()=>setProductQuantity((prev)=> prev + 1)}>+</button>
                        </div>

                        <div className="selectSize">
                            <div className="selectSizeHeading">Select Size</div>
                            <div className="sizeButtons">
                                <button>S</button>
                                <button>M</button>
                                <button>L</button>
                                <button>XL</button>
                                <button>2XL</button>
                                <button>3XL</button>
                            </div>
                        </div>

                        <div className="actionButtons">
                            <button className="addToCart"> <img src={addToCartIcon} alt=''></img>Add to Cart</button>
                            <button className="addToFavourite"><img src={addToFavouriteIcon} alt=''></img>Add to Favourites</button>
                        </div>
                    </div>
                </div>
            }

        </div>
    )
}

export default Product;